name: libqrencode

on:
  push:

jobs:
  docker:
    uses: WaterLemons2k/Docker/.github/workflows/docker.yml@main
    with:
      tags: |
        waterlemons2k/libqrencode
        waterlemons2k/libqrencode:3.4.3
    secrets:
      TOKEN: ${{ secrets.TOKEN }}